
export const Create = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}

export const CreateApplications = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}

export const CreateDetails = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}

export const CreateDelete = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}